# Generated by Django 5.0.7 on 2024-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='num_employees',
            new_name='number_employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='university',
            field=models.CharField(max_length=200),
        ),
    ]
