# Generated by Django 5.0.7 on 2024-07-25 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('vacancies', models.IntegerField()),
                ('pay_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('eligible_candidates', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employer')),
            ],
        ),
    ]
